---
abstract: 'perl binary manager'
author:
  - 'Tokuhiro Matsuno <tokuhirom@gmail.com>'
build_requires:
  Test::More: 0.98
  Test::Requires: 0
  lib::core::only: 0
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Minilla/v0.0.56, CPAN::Meta::Converter version 2.130880'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: plenv
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
provides:
  App::plenv:
    file: lib/App/plenv.pm
    version: v1.4.13
requires:
  App::cpanminus: 0
  Devel::PatchPerl: 0.84
  Perl::Build: 0.13
  Pod::Find: 0
  Pod::Usage: 0
  perl: 5.008002
resources:
  bugtracker: https://github.com/tokuhirom/plenv/issues
  homepage: https://github.com/tokuhirom/plenv
  repository: git://github.com/tokuhirom/plenv.git
version: 1.4.13
x_contributors:
  - 'Masato Ikeda <masato.ikeda@gmail.com>'
  - 'Nishibayashi Takuji <takuji31@gmail.com>'
  - 'xaicron <xaicron@gmail.com>'
  - 'Kozaki, Tsuneaki <kozaki.tsuneaki@gmail.com>'
  - 'moznion <moznion@gmail.com>'
  - 'ks <ks-for-git@live.jp>'
  - 'Tatsuhiko Miyagawa <miyagawa@bulknews.net>'
  - 'Syohei YOSHIDA <syohex@gmail.com>'
