---
abstract: 'perl binary manager'
author:
  - 'Tokuhiro Matsuno <tokuhirom AAJKLFJEF@ GMAIL COM>'
build_requires:
  Test::More: 0.98
  Test::Requires: 0
  lib::core::only: 0
configure_requires:
  Module::Build: 0.38
  Module::Build::Pluggable: 0.05
dynamic_config: 0
generated_by: 'Minilla/v0.0.49, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: plenv
provides:
  App::plenv:
    file: lib/App/plenv.pm
    version: v1.4.8
requires:
  App::cpanminus: 0
  Devel::PatchPerl: 0.84
  Perl::Build: 0.09
  Pod::Find: 0
  Pod::Usage: 0
resources:
  bugtracker: https://github.com/tokuhirom/plenv/issues
  homepage: https://github.com/tokuhirom/plenv
  repository: git://github.com/tokuhirom/plenv.git
version: 1.4.8
